### ISSUE TITLE
Upgrade gulp-sass to solve the node-sass compile issue on recent nodejs version

### ISSUE THREAD

**Issue by liyaodong** [xwp/undercurrent#22]
Hi,

I've tried downgrade my nodejs from 13 to 12, or even 11. but seem like I still can't finish yarn install without see the node-sass error. (actulaly the compile error make my CPU fan like crazy).

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ydli/.npm/_logs/2020-02-18T14_20_12_321Z-debug.log
```

After some spike I found it's because the package gulp-sass version is too low. in order to fix the node-sass compile issue we need to upgrade the gulp-sass. 

FYI the official node-sass has a table about node version:

NodeJS | Minimum node-sass version | Node Module
-- | -- | --
Node 13 | 4.13+ | 79
Node 12 | 4.12+ | 72
Node 11 | 4.10+ | 67
Node 10 | 4.9+ | 64
Node 8 | 4.5.3+ | 57

Is there any plan to upgrade the package version?

Thanks

**Comment by mehigh** [comment]
Thank you. Yes, updating this to a more modern Node should be happening soon. For now you should be able to use node 10 to not be blocked.

**Comment by liyaodong** [comment]
Thanks for the update, seem like gulp-sass not updated as well. maybe gulp-dart-scss is a good option, since it rely on dart-sass no need node gyp to binding c++ stuff. 

https://github.com/mattdsteele/gulp-dart-sass

**Comment by dmao** [comment]
Node version 
`▶ node -v
v13.7.0`

Yarn version
`▶ yarn -v
1.21.1`

NPM version
`▶ npm -v
6.13.7`

I'm not able to recreate the bug. With the current npm package or a local version.
These two commands are working for me (after a `npm init` in an empty directory).
`yarn add -D undercurrent`
`npm install undercurrent --save-dev`

The version of `gulp-sass` inside `package.json` is `^4.0.1`
With the `^` will call already the last version `4.0.2` and it's the last version available. https://github.com/dlmanning/gulp-sass/releases

Screenshot of `yarn.lock`
![Screenshot 2020-02-19 at 14 12 31](https://user-images.githubusercontent.com/1448688/74837512-f1901800-5321-11ea-8994-4bf3fe6fb576.jpg)
